//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0_Framework.Apllication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_0_Framework.Apllication.Resources.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is duplicated.
        /// </summary>
        public static string DuplicatedRecord {
            get {
                return ResourceManager.GetString("DuplicatedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed :(.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and password.
        /// </summary>
        public static string InValidUserNamePassword {
            get {
                return ResourceManager.GetString("InValidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is locked out.
        /// </summary>
        public static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not allowed.
        /// </summary>
        public static string IsNotAllowed {
            get {
                return ResourceManager.GetString("IsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number confirmed.
        /// </summary>
        public static string PhoneNumberConfirm {
            get {
                return ResourceManager.GetString("PhoneNumberConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number has already been verified.
        /// </summary>
        public static string PhoneNumberConfirmBefore {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not confirm! please check your inbox.
        /// </summary>
        public static string PhoneNumberNotConfirm {
            get {
                return ResourceManager.GetString("PhoneNumberNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successed :).
        /// </summary>
        public static string Successed {
            get {
                return ResourceManager.GetString("Successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is taken.
        /// </summary>
        public static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is not exist , your not register.
        /// </summary>
        public static string UserNotRegister {
            get {
                return ResourceManager.GetString("UserNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to send SMS.
        /// </summary>
        public static string WaitingToSendSMS {
            get {
                return ResourceManager.GetString("WaitingToSendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect.
        /// </summary>
        public static string WrongUserPass {
            get {
                return ResourceManager.GetString("WrongUserPass", resourceCulture);
            }
        }
    }
}
